host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/GetBucketReferer/?referer:
        
        get:
            description: Get Bucket Referer操作用于查看bucket的Referer相关配置。Bucket Referer防盗链具体见OSS防盗链。
                    1.	如果Bucket不存在，返回404错误。错误码：NoSuchBucket。
                    2.	只有Bucket的拥有者才能查看Bucket的Referer配置信息，否则返回403 Forbidden错误,错误码：AccessDenied。 
                    3.  如果Bucket未进行Referer相关配置，OSS会返回默认的AllowEmptyReferer值和空的RefererList。

            consumes:
            - application/x-www-form-urlencoded
            parameters: 
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:
                    description: success response
                    schema:
                        type: object
                        properties:
                            RefererConfiguration:
                                description:  保存Referer配置内容的容器    类型：容器     子节点：AllowEmptyReferer节点、RefererList节点    父节点：无 
                                in: formData
                                name: RefererConfiguration
                                type: object
                                properties:
                                    AllowEmptyReferer:
                                        default: 'true'
                                        description:  指定是否允许referer字段为空的请求访问。   类型：枚举字符串 有效值：true 或 false`默认值：true  父节点：RefererConfiguration 
                                        enum: 
                                        - true
                                        - false
                                        in: formData
                                        name: AllowEmptyReferer
                                        type: string
                                    RefererList:
                                        description:  保存referer访问白名单的容器。  类型：容器  父节点：RefererConfiguration  子节点：Referer 
                                        in: formData
                                        name: RefererList
                                        type: object
                                        properties:
                                            Referer:
                                                description:  指定一条referer访问白名单。  类型：字符串  父节点：RefererList 
                                                in: formData
                                                name: Referer
                                                type: string
                              
                403:
                    description: 只有Bucket的拥有者才能查看Bucket的Referer配置信息，否则返回403 Forbidden错误,错误码：AccessDenied。
                404:
                    description: 如果Bucket不存在，返回404错误。错误码：NoSuchBucket。
        summary: 查看Bucket的防盗链规则
        x-requestformat: '
                        GET /?referer HTTP/1.1
                        Host: BucketName.oss.aliyuncs.com
                        Date: GMT Date
                        Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        Get /?referer HTTP/1.1
                        Host: oss-example.oss.aliyuncs.com
                        Date: Thu, 13 Sep 2012 07:51:28 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc: BuG4rRK+zNhH1AcF51NNHD39zXw=
                        '
            id: 1
        -   description: '
                        Get /?referer HTTP/1.1
                        Host: oss-example.oss.aliyuncs.com
                        Date: Thu, 13 Sep 2012 07:51:28 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc: BuG4rRK+zNhH1AcF51NNHD39zXw=

                        '
            id: 2
        x-responsesample:
        -   description: '
                        HTTP/1.1 200
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Thu, 13 Sep 2012 07:51:28 GMT
                        Connection: keep-alive
                        Content-Length: 218
                        Server: AliyunOSS
                        <?xml version="1.0" encoding="UTF-8"?>
                        <RefererConfiguration>
                        <AllowEmptyReferer>true</AllowEmptyReferer >
                            <RefererList>
                                <Referer> http://www.aliyun.com</Referer>
                                <Referer> https://www.aliyun.com</Referer>
                                <Referer> http://www.*.com</Referer>
                                <Referer> https://www.?.aliyuncs.com</Referer>
                            </RefererList>
                        </RefererConfiguration>

                        '
            id: 1
            note: 已设置Referer规则的返回示例
        -   description: '
                        HTTP/1.1 200
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Thu, 13 Sep 2012 07:56:46 GMT
                        Connection: keep-alive
                        Content-Length: 308
                        Server: AliyunOSS
                        <?xml version="1.0" encoding="UTF-8"?>
                        <RefererConfiguration>
                        <AllowEmptyReferer>true</AllowEmptyReferer > < RefererList />
                        </RefererConfiguration>

                        '
            id: 2
            note: 未设置Referer规则的返回示例