host: ecs.aliyuncs.com
info:
    description: 云服务器（Elastic Compute Service，简称 ECS）是一种简单高效、处理能力可弹性伸缩的计算服务，帮助您快速构建更稳定、安全的应用，提升运维效率，降低 IT 成本，使您更专注于核心业务创新。
    title: instance
    version: '1.0'
paths:
    /ModifyInstanceAttribute:
        get:
            consumes:
            - application/x-www-form-urlencoded
            description: '<h2 id="h2--em-em-"><a name="<em>描述</em>" class="reference-link"></a><span class="header-link octicon octicon-link"></span><em>描述</em></h2><p>修改实例密码、实例名称、安全组等属性信息。</p><ul><li>此操作只修改参数中显式指定了的属性，没有指定的属性将不会发生改变。</li><li>重置实例的密码，状态为 Deleted 或 Starting 的实例不可以进行此操作。重置密码需要在控制台或使用OPENAPI重启实例后才能生效，在实例内部的重启将不会生效。</li><li>被安全控制在实例的 <code>OperationLocks</code> 中标记了 <code>"LockReason" : "security"</code>的锁定状态时，不能修改密码。</li><li>当实例在stopped状态且满足<a href="/document_detail/49121.html">实例自定义数据</a>使用限制时，可以修改自定义数据.</li><li>UserData以Base64的方式进行编码。UserData将以不加密的方式传入，所以请不要将机密的信息（比如密码，私钥数据等）以明文的方式传入，如果必须传入，建议进行加密后，然后以Base64的方式进行编码传入，在实例内部以同样的方式反解密。</li></ul>'
            parameters:
            -   description: 系统规定参数，取值：ModifyInstanceAttribute
                enum:
                - ModifyInstanceAttribute
                in: query
                name: Action
                required: true
                type: string
            -   description: 指定的实例 ID
                in: query
                name: InstanceId
                required: true
                type: string
            -   description: 实例的显示名称，[2, 128] 英文或中文字符，必须以大小字母或中文开头，可包含数字，”.”，”_“或”-“。不能以 http:// 和 https:// 开头。
                in: query
                maxLength: 128
                minLength: 2
                name: InstanceName
                required: false
                type: string
            -   default: 空
                description: 实例的描述，[2, 256] 个字符。实例描述会显示在控制台。默认为空。不能以 http:// 和 https:// 开头。
                in: query
                maxLength: 256
                minLength: 2
                name: Description
                required: false
                type: string
            -   description: '重置为用户指定的密。8-30个字符，必须同时包含三项（大、小写字母，数字和特殊符号）。支持以下特殊字符：( ) ` ~ ! @ # $ % ^ &amp; * - + = |{ } [ ] : ;‘ &lt; &lt; , . ? /<br>如果传入 Password 参数，请务必使用 HTTPS 协议调用 API 以避免可能发生的密码泄露。'
                in: query
                maxLength: 30
                minLength: 8
                name: Password
                required: false
                type: string
            -   description: 表示操作系统内部的计算机名，最少 2 字符，”.”和”-“是不能作为 hostname 的首尾字符，不能连续使用。<br>Windows 平台最长为 15 字符，允许字母（不限制大小写）、数字和”-“组成，不支持点号（”.”），不能全是数字。<br>其他（Linux 等）平台最长为 30 字符，允许支持多个点号，点之间为一段，每段允许字母（不限制大小写）、数字和”-“组成。
                in: query
                minLength: 2
                name: HostName
                required: false
                type: string
            -   description: 实例自定义数据，需要以base64的方式编码，原始数据最多为16KB。
                in: query
                maxLength: 16384
                name: UserData
                required: false
                type: string
            produces:
            - application/xml
            - application/json
            responses:
                200:
                    description: Accept
                    schema:
                        properties: {}
                        type: object
                400:
                    description: '{code: IdempotentParameterMismatch, describeen: The request is retried with updated parameters.}, {code: IllegalTimestamp, describeen: The input parameter “Timestamp” that is mandatory for processing this request is not supplied.}, {code: IncompleteSignature, describeen: The request signature does not conform to Aliyun standards.}, {code: InsufficientBalance, describeen: Your account does not have enough balance.}, {code: InvalidAccessKeyId.NotFound, describeen: The specified Access Key ID does not exist.}, {code: InvalidOwner, describeen: OwnerId and OwnerAccount can’t be used at one API access.}, {code: InvalidOwnerAccount, describeen: The specified OwnerAccount is not valid.}, {code: InvalidOwnerId, describeen: The specified OwnerId is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureMethod” is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureVersion” is not valid.}, {code: InvalidParameter,
                        describeen: The specified parameter is not valid}, {code: InvalidParameter, describeen: The specified parameter “Action or Version” is not valid.}, {code: InvalidParameter.IsNull, describeen: The required parameter must be not null.}, {code: MissingParameter, describeen: The input parameter “Action” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “AccessKeyId” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Signature” that is mandatory for processing the request is not supplied.}, {code: MissingParameter, describeen: The input parameter “TimeStamp” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Version” that is mandatory for processing this request is not supplied}, {code: SignatureNonceUsed, describeen: The request signature nonce has been used.},
                        {code: Throttling, describeen: You have made too many requests within a short time; your request is denied due to request throttling.}, {code: UnsupportedParameter, describeen: },{code: InvalidInstanceName.Malformed, describeen: The specified parameter “InstanceName” is not valid., describecn: 指定的 InstanceName 格式不合法}, {code: InvalidDescription.Malformed, describeen: The specified parameter “Description” is not valid., describecn: 指定的 Description 格式不合法}, {code: InvalidHostPassword.Malformed, describeen: The specified parameter “Password” is not valid., describecn: 指定的 Password 格式不合法}, {code: InvalidHostName.Malformed, describeen: The specified parameter “HostName” is not valid., describecn: 指定的 HostName 格式不合法}, {code: InvalidPassword.Malformed, describeen: The specified parameter “Password” is not valid., describecn: 指定的Password格式不合法}, {code: InvalidDescription.Malformed, describeen: The specified destination image description is wrongly formed., describecn: 指定的Description不合法},
                        {code: InvalidUserData.SizeExceeded, describeen: The specified parameter “UserData” exceeds the size., describecn: 指定的UserData过长}, {code: InvalidUserData.NotSupported, describeen: The specified parameter “UserData” only support the vpc and IoOptimized Instance., describecn: UserData只能使用在VPC和io优化实例上}'
                403:
                    description: '{code: ChargeTypeViolation, describeen: The operation is not permitted due to charge type of the instance.}, {code: Forbidden.AccessKeyDisabled, describeen: The Access Key is disabled.}, {code: Forbidden.NotSupportRAM, describeen: This action does not support accessed by RAM mode.}, {code: Forbidden.RAM, describeen: User not authorized to operate on the specified resource, or this API doesn&#39;t support RAM.}, {code: Forbidden.RiskControl, describeen: This operation is forbidden by Aliyun RiskControl system.}, {code: Forbidden.SubUser, describeen: The specified action is not available for you.}, {code: Forbidden.Unauthorized, describeen: User not authorized to operate on the specified resource.}, {code: InvalidAccount.NotFound, describeen: The specified Account does not exist.}, {code: InvalidAction, describeen: Specified action is not valid.}, {code: InvalidIdempotenceParameter.Mismatch, describeen: The specified parameters are different from before.},
                        {code: InvalidParameter.OwnerAccount, describeen: OwnerAccount is Invalid.}, {code: InvalidParameter.ResourceOwnerAccount, describeen: ResourceOwnerAccount is Invalid.}, {code: LastTokenProcessing, describeen: The last token request is processing.}, {code: MissingParameter, describeen: The input parameter OwnerId,OwnerAccount that is mandatory for processing this request is not supplied.}, {code: RealNameAuthenticationError, describeen: Your account has not passed the real-name authentication yet.}, {code: UnsupportedHTTPMethod, describeen: This http method is not supported.},{code: IncorrectInstanceStatus, describeen: The current status of the resource does not support this operation., describecn: 该资源目前的状态不支持此操作}, {code: InstanceLockedForSecurity, describeen: The specified operation is denied as your instance is locked for security reasons., describecn: 该资源目前被安全锁定被拒绝操作}, {code: OperationDenied, describeen: The instance amount in the specified SecurityGroup reach
                        its limit., describecn: 指定安全组中实例数量达到上限}, {code: OperationDenied, describeen: The current status of the resource does not support this operation., describecn: 指定资源的状态不支持该操作}, {code: OperationDenied, describeen: The Specified operation is denied as your instance is locked for security reasons., describecn: 实例已经被锁定}, {code: InvalidUserData.Forbidden, describeen: User not authorized to input the parameter “UserData”please apply for permission “UserData”, describecn: 用户没有权限使用UserData}'
                404:
                    description: '{code: InvalidDiskId.NotFound, describeen: The specified DiskId does not exist.}, {code: InvalidImageId.NotFound, describeen: The specified ImageId does not exist.}, {code: InvalidInstanceId.NotFound, describeen: The specified InstanceId does not exist.}, {code: InvalidRegionId.NotFound, describeen: The specified RegionId does not exist.}, {code: InvalidSecurityGroupId.NotFound, describeen: The specified SecurityGroupId does not exist.}, {code: InvalidSnapshotId.NotFound, describeen: The specified SnapshotId does not exist.},{code: InvalidInstanceId.NotFound, describeen: The specified InstanceId does not exist., describecn: 指定的 InstanceId 不存在}, {code: InvalidSecurityGroupId.NotFound, describeen: The specified SecurityGroupId does not exist., describecn: 指定的SecurityGroupId不存在}, {code: HOSTNAME_ILLEGAL, describeen: hostname is not valid., describecn: 指定的hostname参数不合法}'
                409:
                    description: '{code: OperationConflict, describeen: Request was denied due to conflict with a previous request.}'
                500:
                    description: '{code: InternalError, describeen: The request processing has failed due to some unknown error, exception or failure.}'
                503:
                    description: '{code: ServiceUnavailable, describeen: The request has failed due to a temporary failure of the server.}, {code: ServiceUnavailable.RegionMaintaining, describeen: System maintenance is in progress on the selected region, please wait a few minutes before trying again.}'
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        summary: 修改 ECS 实例密码、实例名称、安全组等属性信息
        x-requestsample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=ModifyInstanceAttribute</span></code></li><li class="L1"><code><span class="pun">&amp;</span><span class="typ">InstanceId</span><span class="pun">=</span><span class="pln">i</span><span class="pun">-</span><span class="pln">instance1</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">Password</span><span class="pun">=</span><span class="pln">pwd</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 1
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=ModifyInstanceAttribute</span></code></li><li class="L1"><code><span class="pun">&amp;</span><span class="typ">InstanceId</span><span class="pun">=</span><span class="pln">i</span><span class="pun">-</span><span class="pln">instance1</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">Password</span><span class="pun">=</span><span class="pln">pwd</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 2
        x-responsesample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-xml"><span class="tag">&lt;ModifyInstanceAttributeResponse&gt;</span></code></li><li class="L1"><code class="lang-xml"><span class="pln">    </span><span class="tag">&lt;RequestId&gt;</span><span class="pln">473469C7-AA6F-4DC5-B3DB-A3DC0DE3C83E</span><span class="tag">&lt;/RequestId&gt;</span></code></li><li class="L2"><code class="lang-xml"><span class="tag">&lt;/ModifyInstanceAttributeResponse&gt;</span></code></li></ol></pre>
            id: 1
            note: XML格式
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-json"><span class="pun">{</span></code></li><li class="L1"><code class="lang-json"><span class="pln">    </span><span class="str">"RequestId"</span><span class="pun">:</span><span class="pln"> </span><span class="str">"473469C7-AA6F-4DC5-B3DB-A3DC0DE3C83E"</span></code></li><li class="L2"><code class="lang-json"><span class="pun">}</span></code></li></ol></pre>
            id: 2
            note: JSON格式
    /public:
        request:
            parameters:
            -   description: 返回值的类型，支持 JSON 与 XML。默认为 XML。
                enum:
                - XML
                - JSON
                default: XML
                in: query
                name: Format
                required: false
                type: string
            -   description: API 版本号，为日期形式：YYYY-MM-DD，本版本对应为 2014-05-26。
                in: query
                name: Version
                required: true
                type: string
            -   description: 阿里云颁发给用户的访问服务所用的密钥 ID。
                in: query
                name: AccessKeyId
                required: true
                type: string
            -   description: 签名结果串，关于签名的计算方法，请参见&lt;<a href="/document_detail/25492.html">签名机制</a>&gt;。
                in: query
                name: Signature
                required: true
                type: string
            -   description: 签名方式，目前支持 HMAC-SHA1。
                in: query
                name: SignatureMethod
                required: true
                type: string
            -   description: '        请求的时间戳。日期格式按照 <a href="/document_detail/25696.html">ISO8601</a> 标准表示，并需要使用 UTC 时间。格式为： <br />        YYYY-MM-DDThh:mm:ssZ <br />        例如，2014-05-26T12:00:00Z（为北京时间 2014 年 5 月 26 日 20 点 0 分 0 秒）。    '
                in: query
                name: Timestamp
                required: true
                type: string
            -   description: 签名算法版本，目前版本是 1.0。
                in: query
                name: SignatureVersion
                required: true
                type: string
            -   description: 唯一随机数，用于防止网络重放攻击。用户在不同请求间要使用不同的随机数值
                in: query
                name: SignatureNonce
                required: true
                type: string
            -   description: '        本次 API 请求访问到的资源拥有者账户，即登录用户名。 <br />        此参数的使用方法，详见&lt; <a href="/document_detail/25494.html">借助 RAM 实现子账号对主账号的 ECS 资源访问</a> &gt;，（只能在 <a href="/document_detail/25496.html">RAM 中可对 ECS 资源进行授权的 Action</a> 中才能使用此参数，否则访问会被拒绝）    '
                in: query
                name: '        ResourceOwnerAccount    '
                required: false
                type: string
        response:
            RequestId:
                description: 用户发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: body
                name: RequestId
                type: string
swagger: '2.0'
x-vee: 2.0 AS
