host: ecs.aliyuncs.com
info:
    description: 云服务器（Elastic Compute Service，简称 ECS）是一种简单高效、处理能力可弹性伸缩的计算服务，帮助您快速构建更稳定、安全的应用，提升运维效率，降低 IT 成本，使您更专注于核心业务创新。
    title: instance
    version: '1.0'
paths:
    /DeleteImage:
        get:
            consumes:
            - application/x-www-form-urlencoded
            description: <h2 id="h2--em-em-"><a name="<em>描述</em>" class="reference-link"></a><span class="header-link octicon octicon-link"></span><em>描述</em></h2><p>删除指定的用户自定义镜像。镜像删除之后将不能再用于创建、重置ECS实例。</p><p>如果指定的镜像不存在，则请求将被忽略.</p>
            parameters:
            -   description: 系统规定参数，取值：DeleteImage
                enum:
                - DeleteImage
                in: query
                name: Action
                required: true
                type: string
            -   description: 镜像所在的 Region ID。Region ID 的列表详见 <a href="/document_detail/40654.html">地域列表</a>。
                in: query
                name: RegionId
                required: true
                type: string
            -   description: 镜像 ID
                in: query
                name: ImageId
                required: true
                type: string
            -   default: 'false'
                description: 可选值：true 和 false。默认值为 false。当设置为 true 时，删除镜像将不校验当前镜像是否保有其他实例。
                enum:
                - 'true'
                - 'false'
                in: query
                name: Force
                required: false
                type: string
            produces:
            - application/xml
            - application/json
            responses:
                200:
                    description: Accept
                    schema:
                        properties: {}
                        type: object
                400:
                    description: '{code: IdempotentParameterMismatch, describeen: The request is retried with updated parameters.}, {code: IllegalTimestamp, describeen: The input parameter “Timestamp” that is mandatory for processing this request is not supplied.}, {code: IncompleteSignature, describeen: The request signature does not conform to Aliyun standards.}, {code: InsufficientBalance, describeen: Your account does not have enough balance.}, {code: InvalidAccessKeyId.NotFound, describeen: The specified Access Key ID does not exist.}, {code: InvalidOwner, describeen: OwnerId and OwnerAccount can’t be used at one API access.}, {code: InvalidOwnerAccount, describeen: The specified OwnerAccount is not valid.}, {code: InvalidOwnerId, describeen: The specified OwnerId is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureMethod” is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureVersion” is not valid.}, {code: InvalidParameter,
                        describeen: The specified parameter is not valid}, {code: InvalidParameter, describeen: The specified parameter “Action or Version” is not valid.}, {code: InvalidParameter.IsNull, describeen: The required parameter must be not null.}, {code: MissingParameter, describeen: The input parameter “Action” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “AccessKeyId” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Signature” that is mandatory for processing the request is not supplied.}, {code: MissingParameter, describeen: The input parameter “TimeStamp” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Version” that is mandatory for processing this request is not supplied}, {code: SignatureNonceUsed, describeen: The request signature nonce has been used.},
                        {code: Throttling, describeen: You have made too many requests within a short time; your request is denied due to request throttling.}, {code: UnsupportedParameter, describeen: }'
                403:
                    description: '{code: ChargeTypeViolation, describeen: The operation is not permitted due to charge type of the instance.}, {code: Forbidden.AccessKeyDisabled, describeen: The Access Key is disabled.}, {code: Forbidden.NotSupportRAM, describeen: This action does not support accessed by RAM mode.}, {code: Forbidden.RAM, describeen: User not authorized to operate on the specified resource, or this API doesn&#39;t support RAM.}, {code: Forbidden.RiskControl, describeen: This operation is forbidden by Aliyun RiskControl system.}, {code: Forbidden.SubUser, describeen: The specified action is not available for you.}, {code: Forbidden.Unauthorized, describeen: User not authorized to operate on the specified resource.}, {code: InvalidAccount.NotFound, describeen: The specified Account does not exist.}, {code: InvalidAction, describeen: Specified action is not valid.}, {code: InvalidIdempotenceParameter.Mismatch, describeen: The specified parameters are different from before.},
                        {code: InvalidParameter.OwnerAccount, describeen: OwnerAccount is Invalid.}, {code: InvalidParameter.ResourceOwnerAccount, describeen: ResourceOwnerAccount is Invalid.}, {code: LastTokenProcessing, describeen: The last token request is processing.}, {code: MissingParameter, describeen: The input parameter OwnerId,OwnerAccount that is mandatory for processing this request is not supplied.}, {code: RealNameAuthenticationError, describeen: Your account has not passed the real-name authentication yet.}, {code: UnsupportedHTTPMethod, describeen: This http method is not supported.},{code: ImageUsingByInstance, describeen: The specified image has been used to create instances., describecn: 指定的镜像 ID 还存在保有实例，不能删除该镜像}, {code: ImageIsCreating, describeen: The specified image is being created., describecn: 指定镜像正在创建中}, {code: ImageUseShared, describeen: The specified image has been shared to others., describecn: 指定镜像已经共享}, {code: OperationDenied.ImageCopying, describeen: The specified
                        image is being copied., describecn: 镜像正在复制中}'
                404:
                    description: '{code: InvalidDiskId.NotFound, describeen: The specified DiskId does not exist.}, {code: InvalidImageId.NotFound, describeen: The specified ImageId does not exist.}, {code: InvalidInstanceId.NotFound, describeen: The specified InstanceId does not exist.}, {code: InvalidRegionId.NotFound, describeen: The specified RegionId does not exist.}, {code: InvalidSecurityGroupId.NotFound, describeen: The specified SecurityGroupId does not exist.}, {code: InvalidSnapshotId.NotFound, describeen: The specified SnapshotId does not exist.},{code: InvalidRegionId.NotFound, describeen: The specified region does not exist., describecn: 无效的 RegionId 取值（实际情况也可能是该用户无权使用此 Region）。RegionId 的列表详见 <a href="/document_detail/40654.html">地域列表</a>。}'
                409:
                    description: '{code: OperationConflict, describeen: Request was denied due to conflict with a previous request.}'
                500:
                    description: '{code: InternalError, describeen: The request processing has failed due to some unknown error, exception or failure.}'
                503:
                    description: '{code: ServiceUnavailable, describeen: The request has failed due to a temporary failure of the server.}, {code: ServiceUnavailable.RegionMaintaining, describeen: System maintenance is in progress on the selected region, please wait a few minutes before trying again.}'
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        summary: 删除指定的用户自定义镜像
        x-requestsample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=DeleteImage</span></code></li><li class="L1"><code><span class="pun">&amp;</span><span class="typ">RegionId</span><span class="pun">=</span><span class="pln">cn</span><span class="pun">-</span><span class="pln">hangzhou</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">ImageId</span><span class="pun">=</span><span class="pln">m</span><span class="pun">-</span><span class="lit">63DFD5FB2</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 1
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=DeleteImage</span></code></li><li class="L1"><code><span class="pun">&amp;</span><span class="typ">RegionId</span><span class="pun">=</span><span class="pln">cn</span><span class="pun">-</span><span class="pln">hangzhou</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">ImageId</span><span class="pun">=</span><span class="pln">m</span><span class="pun">-</span><span class="lit">63DFD5FB2</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 2
        x-responsesample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-xml"><span class="tag">&lt;DeleteImageResponse&gt;</span></code></li><li class="L1"><code class="lang-xml"><span class="pln">     </span><span class="tag">&lt;RequestId&gt;</span><span class="pln">CEF72CEB-54B6-4AE8-B225-F876FF7BA984</span><span class="tag">&lt;/RequestId&gt;</span></code></li><li class="L2"><code class="lang-xml"><span class="tag">&lt;/DeleteImageResponse&gt;</span></code></li></ol></pre>
            id: 1
            note: XML格式
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-json"><span class="pun">{</span></code></li><li class="L1"><code class="lang-json"><span class="pln">    </span><span class="str">"RequestId"</span><span class="pun">:</span><span class="pln"> </span><span class="str">"CEF72CEB-54B6-4AE8-B225-F876FF7BA984"</span></code></li><li class="L2"><code class="lang-json"><span class="pun">}</span></code></li></ol></pre>
            id: 2
            note: JSON格式
    /public:
        request:
            parameters:
            -   default: XML
                description: 返回值的类型，支持 JSON 与 XML。默认为 XML。
                enum:
                - XML
                - JSON
                in: query
                name: Format
                required: false
                type: string
            -   description: API 版本号，为日期形式：YYYY-MM-DD，本版本对应为 2014-05-26。
                in: query
                name: Version
                required: true
                type: string
            -   description: 阿里云颁发给用户的访问服务所用的密钥 ID。
                in: query
                name: AccessKeyId
                required: true
                type: string
            -   description: 签名结果串，关于签名的计算方法，请参见&lt;<a href="/document_detail/25492.html">签名机制</a>&gt;。
                in: query
                name: Signature
                required: true
                type: string
            -   description: 签名方式，目前支持 HMAC-SHA1。
                in: query
                name: SignatureMethod
                required: true
                type: string
            -   description: '        请求的时间戳。日期格式按照 <a href="/document_detail/25696.html">ISO8601</a> 标准表示，并需要使用 UTC 时间。格式为： <br />        YYYY-MM-DDThh:mm:ssZ <br />        例如，2014-05-26T12:00:00Z（为北京时间 2014 年 5 月 26 日 20 点 0 分 0 秒）。    '
                in: query
                name: Timestamp
                required: true
                type: string
            -   description: 签名算法版本，目前版本是 1.0。
                in: query
                name: SignatureVersion
                required: true
                type: string
            -   description: 唯一随机数，用于防止网络重放攻击。用户在不同请求间要使用不同的随机数值
                in: query
                name: SignatureNonce
                required: true
                type: string
            -   description: '本次 API 请求访问到的资源拥有者账户，即登录用户名。 <br />        此参数的使用方法，详见&lt; <a href="/document_detail/25494.html">借助 RAM 实现子账号对主账号的 ECS 资源访问</a> &gt;，（只能在 <a href="/document_detail/25496.html">RAM 中可对 ECS 资源进行授权的 Action</a> 中才能使用此参数，否则访问会被拒绝）    '
                in: query
                name: ResourceOwnerAccount
                required: false
                type: string
        response:
            RequestId:
                description: 用户发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: body
                name: RequestId
                type: string
swagger: '2.0'
x-vee: 2.0 AS
