host: ecs.aliyuncs.com
info:
    description: 云服务器（Elastic Compute Service，简称 ECS）是一种简单高效、处理能力可弹性伸缩的计算服务，帮助您快速构建更稳定、安全的应用，提升运维效率，降低 IT 成本，使您更专注于核心业务创新。
    title: instance
    version: '1.0'
paths:
    /ReplaceSystemDisk:
        get:
            consumes:
            - application/x-www-form-urlencoded
            description: '<h2 id="h2-u63CFu8FF0"><a name="描述" class="reference-link"></a><span class="header-link octicon octicon-link"></span>描述</h2><p>更换 ECS 实例的系统盘。您可以通过更换系统盘更换 ECS 实例的操作系统。</p><p>使用该接口时，需要注意的是：</p><ul><li>系统盘类型不能更换。</li><li>更换系统盘时，会改变 ECS 实例的系统盘磁盘 ID。</li><li>更换系统盘时，不改变系统盘的磁盘种类和付费方式，同时原系统盘将被释放。</li><li>更换系统盘时，实例的状态必须为已停止（<code>Stopped</code>）状态，且实例的 <code>OperationLocks</code> 中没有标记 <code>"LockReason" : "security"</code> 的锁定状态，且实例不能为欠费状态。</li><li>可以通过指定参数 <code>SystemDisk.Size</code> 重新指定系统盘的容量大小，其中参数 <code>SystemDisk.Size</code> 的值必须大于等于 max{40, 更换前的系统盘容量}。超过 max{40, 更换前的系统盘容量} 的磁盘容量部分，将收取额外费用。</li></ul>'
            parameters:
            -   description: 系统规定参数。取值：ReplaceSystemDisk
                enum:
                - ReplaceSystemDisk
                in: query
                name: Action
                required: true
                type: string
            -   description: 指定实例的 ID。
                in: query
                name: InstanceId
                required: true
                type: string
            -   description: 重置系统时使用的镜像 ID。
                in: query
                name: ImageId
                required: true
                type: string
            -   description: '实例的密码。<ul><li>长度为 [8, 30] 个字符，必须同时包含三类不同的字符（大、小写字母，数字和特殊符号）。</li><li>支持以下特殊字符：( ) ` ~ ! @ # $ % ^ &amp; * - + = |{ } [ ] : ;‘ &lt; &gt; , . ? /</li></ul>如果传入 <code>Password</code> 参数，请务必使用 HTTPS 协议调用 API，避免密码泄露。'
                enum:
                - Password
                in: query
                maxLength: 30
                minLength: 8
                name: Password
                required: false
                type: string
            -   default: 空
                description: 密钥对名称。<ul> <li>Windows ECS 实例，忽略该参数。默认为空。即使填写了该参数，仍旧只执行 <code>Password</code> 的内容。</li> <li>Linux ECS 实例的密码登录方式会被初始化成禁止。</li></ul>
                in: query
                name: KeyPairName
                required: false
                type: string
            -   description: 新的系统盘容量，单位为 GB。取值范围为：<ul><li>[Max{40, ImageId.size}, 500]。</li></ul> 默认值：Max{40, ImageId.size}
                in: query
                maximum: 500
                name: SystemDisk.Size
                required: false
                type: integer
            -   description: 用于保证请求的幂等性。由客户端生成该参数值，要保证在不同请求间唯一，最大不能超过 64 个 ASCII 字符。<br>具体参见附录：<a href="/document_detail/25693.html">如何保证幂等性</a>。
                in: query
                maxLength: 64
                name: ClientToken
                required: false
                type: string
            -   description: 是否开启安全加固，取值范围：<ul><li>Active：启用安全加固，只对系统镜像生效</li><li>Deactive：不启用安全加固，对所有镜像类型生效</li></ul>
                enum:
                - Active
                - Deactive
                in: query
                name: SecurityEnhancementStrategy
                required: false
                type: string
            produces:
            - application/xml
            - application/json
            responses:
                200:
                    description: Accept
                    schema:
                        properties:
                            DiskId:
                                description: 新系统盘的磁盘 ID
                                name: DiskId
                                type: string
                        type: object
                400:
                    description: '{code: IdempotentParameterMismatch, describeen: The request is retried with updated parameters.}, {code: IllegalTimestamp, describeen: The input parameter “Timestamp” that is mandatory for processing this request is not supplied.}, {code: IncompleteSignature, describeen: The request signature does not conform to Aliyun standards.}, {code: InsufficientBalance, describeen: Your account does not have enough balance.}, {code: InvalidAccessKeyId.NotFound, describeen: The specified Access Key ID does not exist.}, {code: InvalidOwner, describeen: OwnerId and OwnerAccount can’t be used at one API access.}, {code: InvalidOwnerAccount, describeen: The specified OwnerAccount is not valid.}, {code: InvalidOwnerId, describeen: The specified OwnerId is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureMethod” is not valid.}, {code: InvalidParamater, describeen: The specified parameter “SignatureVersion” is not valid.}, {code: InvalidParameter,
                        describeen: The specified parameter is not valid}, {code: InvalidParameter, describeen: The specified parameter “Action or Version” is not valid.}, {code: InvalidParameter.IsNull, describeen: The required parameter must be not null.}, {code: MissingParameter, describeen: The input parameter “Action” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “AccessKeyId” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Signature” that is mandatory for processing the request is not supplied.}, {code: MissingParameter, describeen: The input parameter “TimeStamp” that is mandatory for processing this request is not supplied}, {code: MissingParameter, describeen: The input parameter “Version” that is mandatory for processing this request is not supplied}, {code: SignatureNonceUsed, describeen: The request signature nonce has been used.},
                        {code: Throttling, describeen: You have made too many requests within a short time; your request is denied due to request throttling.}, {code: UnsupportedParameter, describeen: },{code: InvalidParameter.Conflict, describeen: The specified image does not support the specified instance type., describecn: 指定的镜像不支持创建这一类规格的实例。}, {code: InvalidPassword.Malformed, describeen: The specified parameter “Password” is not valid., describecn: 指定的 Password 格式不合法。}, {code: InvalidSystemDiskSize, describeen: The specified parameter SystemDisk.Size is invalid., describecn: 指定的参数 SystemDisk.Size 不合法。}, {code: InvalidSystemDiskSize.ImageNotSupportResize, describeen: The specified image does not support resize., describecn: 指定的镜像不支持磁盘扩容。}, {code: InvalidSystemDiskSize.ValueNotSupported, describeen: The specified parameter SystemDisk.Size is invalid., describecn: 指定的参数 SystemDisk.Size 不合法。}, {code: OperationDenied, describeen: The specified image contains the snapshot of the data disk,does
                        not support this operation., describecn: 包含数据盘快照的镜像不能进行更换系统盘操作。}'
                403:
                    description: '{code: ChargeTypeViolation, describeen: The operation is not permitted due to charge type of the instance.}, {code: Forbidden.AccessKeyDisabled, describeen: The Access Key is disabled.}, {code: Forbidden.NotSupportRAM, describeen: This action does not support accessed by RAM mode.}, {code: Forbidden.RAM, describeen: User not authorized to operate on the specified resource, or this API doesn&#39;t support RAM.}, {code: Forbidden.RiskControl, describeen: This operation is forbidden by Aliyun RiskControl system.}, {code: Forbidden.SubUser, describeen: The specified action is not available for you.}, {code: Forbidden.Unauthorized, describeen: User not authorized to operate on the specified resource.}, {code: InvalidAccount.NotFound, describeen: The specified Account does not exist.}, {code: InvalidAction, describeen: Specified action is not valid.}, {code: InvalidIdempotenceParameter.Mismatch, describeen: The specified parameters are different from before.},
                        {code: InvalidParameter.OwnerAccount, describeen: OwnerAccount is Invalid.}, {code: InvalidParameter.ResourceOwnerAccount, describeen: ResourceOwnerAccount is Invalid.}, {code: LastTokenProcessing, describeen: The last token request is processing.}, {code: MissingParameter, describeen: The input parameter OwnerId,OwnerAccount that is mandatory for processing this request is not supplied.}, {code: RealNameAuthenticationError, describeen: Your account has not passed the real-name authentication yet.}, {code: UnsupportedHTTPMethod, describeen: This http method is not supported.},{code: ChargeTypeViolation, describeen: The operation is not permitted due to charge type of the instance., describecn: 指定实例的付费方式不支持更换系统盘。}, {code: DiskCreatingSnapshot, describeen: The operation is denied due to a snapshot of the specified disk is not completed yet., describecn: 指定的磁盘正在创建快照。}, {code: ImageNotSubscribed, describeen: The specified image has not be subscribed., describecn: 指定的镜像未在镜像市场订阅。},
                        {code: ImageNotSupportInstanceType, describeen: The specified image don not support the InstanceType instance., describecn: 指定镜像不支持该实例类型。}, {code: ImageRemovedInMarket, describeen: The specified market image is not available, Or the specified user defined image includes product code because it is based on an image subscribed from marketplace, and that image in marketplace includeing exact the same product code has been removed., describecn: 指定的镜像已经从镜像市场中下架。}, {code: IncorrectInstanceStatus, describeen: The current status of the resource does not support this operation., describecn: 指定的实例状态不正确。}, {code: INST_HAS_UNPAID_ORDER, describeen: The instance has unpaid order., describecn: 该实例有未支付的订单。}, {code: InstanceExpiredOrInArrears, describeen: The specified operation is denied as your prepay instance is expired (prepay mode) or in arrears (afterpay mode)., describecn: 指定的实例已欠费。}, {code: InstanceLockedForSecurity, describeen: The instance is locked due to security., describecn:
                        指定的实例被安全锁定。}, {code: IoOptimized.NotSupported, describeen: The specified image is not support IoOptimized Instance., describecn: 镜像必须支持 I/O 优化实例。}, {code: QuotaExceed.BuyImage, describeen: The specified image is from the image market,You have not bought it or your quota has been exceeded., describecn: 指定镜像来自镜像市场，您需要先购买再使用，或者您的镜像个数已超出最大限制。}'
                404:
                    description: '{code: InvalidDiskId.NotFound, describeen: The specified DiskId does not exist.}, {code: InvalidImageId.NotFound, describeen: The specified ImageId does not exist.}, {code: InvalidInstanceId.NotFound, describeen: The specified InstanceId does not exist.}, {code: InvalidRegionId.NotFound, describeen: The specified RegionId does not exist.}, {code: InvalidSecurityGroupId.NotFound, describeen: The specified SecurityGroupId does not exist.}, {code: InvalidSnapshotId.NotFound, describeen: The specified SnapshotId does not exist.},{code: InvalidImageId.NotFound, describeen: The specified ImageId does not exist., describecn: 指定的镜像不存在。}, {code: InvalidInstanceId.NotFound, describeen: The specified InstanceId does not exist., describecn: 指定的实例不存在。}, {code: InvalidSystemDiskSize.LessThanImageSize, describeen: The specified parameter SystemDisk.Size is less than the image size., describecn: 指定的参数 SystemDisk.Size 小于镜像大小。}, {code: InvalidSystemDiskSize.LessThanMinSize,
                        describeen: The specified parameter SystemDisk.Size is less than the min size., describecn: 指定的参数 SystemDisk.Size 小于磁盘大小下限。}, {code: InvalidSystemDiskSize.MoreThanMaxSize, describeen: The specified SystemDisk.Size parameter exceeds the maximum size., describecn: 指定的参数 SystemDisk.Size 大于磁盘大小上限。}, {code: NoSuchResource, describeen: The specified resource is not found., describecn: 指定资源不存在。}'
                409:
                    description: '{code: OperationConflict, describeen: Request was denied due to conflict with a previous request.}'
                500:
                    description: '{code: InternalError, describeen: The request processing has failed due to some unknown error, exception or failure.},{code: OperationDenied, describeen: Internal Error., describecn: 内部错误}'
                503:
                    description: '{code: ServiceUnavailable, describeen: The request has failed due to a temporary failure of the server.}, {code: ServiceUnavailable.RegionMaintaining, describeen: System maintenance is in progress on the selected region, please wait a few minutes before trying again.}'
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        summary: 更换系统盘
        x-requestsample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-shell"><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=ReplaceSystemDisk</span></code></li><li class="L1"><code class="lang-shell"><span class="pun">&amp;</span><span class="typ">InstanceId</span><span class="pun">=</span><span class="pln">i</span><span class="pun">-</span><span class="lit">23jggx34b</span></code></li><li class="L2"><code class="lang-shell"><span class="pun">&amp;</span><span class="typ">ImageId</span><span class="pun">=</span><span class="pln">m</span><span class="pun">-</span><span class="pln">myimage11</span></code></li><li class="L3"><code class="lang-shell"><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 1
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-shell"><span class="pln">https</span><span class="pun">:</span><span class="com">//ecs.aliyuncs.com/?Action=ReplaceSystemDisk</span></code></li><li class="L1"><code class="lang-shell"><span class="pun">&amp;</span><span class="typ">InstanceId</span><span class="pun">=</span><span class="pln">i</span><span class="pun">-</span><span class="lit">23jggx34b</span></code></li><li class="L2"><code class="lang-shell"><span class="pun">&amp;</span><span class="typ">ImageId</span><span class="pun">=</span><span class="pln">m</span><span class="pun">-</span><span class="pln">myimage11</span></code></li><li class="L3"><code class="lang-shell"><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 2
        x-responsesample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-xml"><span class="tag">&lt;ResetDiskResponse&gt;</span></code></li><li class="L1"><code class="lang-xml"><span class="pln">    </span><span class="tag">&lt;DiskId&gt;</span><span class="pln">d-23jbf2v5m</span><span class="tag">&lt;/DiskId&gt;</span></code></li><li class="L2"><code class="lang-xml"><span class="pln">    </span><span class="tag">&lt;RequestId&gt;</span><span class="pln">F3CD6886-D8D0-4FEE-B93E-1B73239673DE</span><span class="tag">&lt;/RequestId&gt;</span></code></li><li class="L3"><code class="lang-xml"><span class="tag">&lt;/ResetDiskResponse&gt;</span></code></li></ol></pre>
            id: 1
            note: XML格式
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-json"><span class="pun">{</span></code></li><li class="L1"><code class="lang-json"><span class="pln">    </span><span class="str">"RequestId"</span><span class="pun">:</span><span class="str">"337568C5-64F3-4B76-8CDD-D3D8C57B5B8C"</span><span class="pun">,</span></code></li><li class="L2"><code class="lang-json"><span class="pln">    </span><span class="str">"DiskId"</span><span class="pun">:</span><span class="str">"d-j6cam2z21u4ks3dj6flb"</span></code></li><li class="L3"><code class="lang-json"><span class="pun">}</span></code></li></ol></pre>
            id: 2
            note: JSON格式
    /public:
        request:
            parameters:
            -   default: XML
                description: 返回值的类型，支持 JSON 与 XML。默认为 XML。
                enum:
                - XML
                - JSON
                in: query
                name: Format
                required: false
                type: string
            -   description: API 版本号，为日期形式：YYYY-MM-DD，本版本对应为 2014-05-26。
                in: query
                name: Version
                required: true
                type: string
            -   description: 阿里云颁发给用户的访问服务所用的密钥 ID。
                in: query
                name: AccessKeyId
                required: true
                type: string
            -   description: 签名结果串，关于签名的计算方法，请参见&lt;<a href="/document_detail/25492.html">签名机制</a>&gt;。
                in: query
                name: Signature
                required: true
                type: string
            -   description: 签名方式，目前支持 HMAC-SHA1。
                in: query
                name: SignatureMethod
                required: true
                type: string
            -   description: '        请求的时间戳。日期格式按照 <a href="/document_detail/25696.html">ISO8601</a> 标准表示，并需要使用 UTC 时间。格式为： <br />        YYYY-MM-DDThh:mm:ssZ <br />        例如，2014-05-26T12:00:00Z（为北京时间 2014 年 5 月 26 日 20 点 0 分 0 秒）。    '
                in: query
                name: Timestamp
                required: true
                type: string
            -   description: 签名算法版本，目前版本是 1.0。
                in: query
                name: SignatureVersion
                required: true
                type: string
            -   description: 唯一随机数，用于防止网络重放攻击。用户在不同请求间要使用不同的随机数值
                in: query
                name: SignatureNonce
                required: true
                type: string
            -   description: '        本次 API 请求访问到的资源拥有者账户，即登录用户名。 <br />        此参数的使用方法，详见&lt; <a href="/document_detail/25494.html">借助 RAM 实现子账号对主账号的 ECS 资源访问</a> &gt;，（只能在 <a href="/document_detail/25496.html">RAM 中可对 ECS 资源进行授权的 Action</a> 中才能使用此参数，否则访问会被拒绝）    '
                in: query
                name: '        ResourceOwnerAccount    '
                required: false
                type: string
        response:
            RequestId:
                description: 用户发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: body
                name: RequestId
                type: string
swagger: '2.0'
x-vee: 2.0 AS
