host: vpc.aliyuncs.com
info:
    description: 专有网络VPC（Virtual Private Cloud）是用户基于阿里云创建的自定义私有网络, 不同的专有网络之间二层逻辑隔离，用户可以在自己创建的专有网络内创建和管理云产品实例，比如ECS、负载均衡、RDS等。
    title: VPC
    version: '1.0'
paths:
    /CreateVpc:
        get:
            consumes:
            - application/x-www-form-urlencoded
            description: <h2 id="h2--em-em-"><a name="<em>描述</em>" class="reference-link"></a><span class="header-link octicon octicon-link"></span><em>描述</em></h2><p>在指定的地域创建 1 个 VPC</p><ul><li>VPC 只能指定 1 个 CidrBlock，CidrBlock 的范围包括 10.0.0.0 / 8、172.16.0.0 / 12 和 192.168.0.0 / 16 及它们的子网，CidrBlock 的掩码为 8 - 24 位，默认为 172.16.0.0 / 12</li><li>VPC 创建后无法修改 CidrBlock</li><li>每个 VPC 包含的云产品实例不能分布在不同地域，可以分布在同一地域的不同可用区内</li><li>每个 VPC 包含的云产品实例数量不超过 10000 个</li><li>创建 VPC 时，会自动创建 1 个虚拟路由器和 1 个路由表。每个 VPC 只允许有 1 个虚拟路由器和 1 个路由表</li><li>每个VPC，支持3个用户侧网络的网段 UserCidr ；如果多个用户侧网段之间存在互相包含(比如10.0.0.0/8和10.1.0.0/16，以10.0.0.0/8实际生效)</li></ul>
            parameters:
            -   description: 系统规定参数，取值：CreateVpc
                enum:
                - CreateVpc
                in: query
                name: Action
                required: true
                type: string
            -   description: 新建的 VPC 所在的地域
                in: query
                name: RegionId
                required: true
                type: string
            -   default: 172.16.0.0/12
                description: 可选值 10.0.0.0/8、172.16.0.0/12和192.168.0.0/16及它们包含的子网。默认是172.16.0.0/12
                enum:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16
                in: query
                name: CidrBlock
                required: false
                type: string
            -   default: ""
                description: VPC 名称，不填则为空，默认值为空。长度范围为2～128个字节。支持英文或中文字符，必须以大小写字母或中文开头，可包含数字， “_” 或 “-” ，不能以 “http://” 或“https://” 开头
                in: query
                maxLength: 128
                minLength: 2
                name: VpcName
                required: false
                type: string
            -   default: ""
                description: 对新建 VPC 的描述，不填则为空，默认值为空。长度范围为2～256个字节。支持英文或中文字符，不能以 “http://” 或“https://” 开头
                in: query
                maxLength: 256
                minLength: 2
                name: Description
                required: false
                type: string
            -   description: 用于保证请求的幂等性。由客户端生成该参数值，要保证在不同请求间唯一，最大不值过 64 个 ASCII 字符，具体参见<a href="https://help.aliyun.com/document_detail/36569.html?spm=5176.doc35737.6.785.bWrLAv" title="如何保证幂等性">如何保证幂等性</a>
                in: query
                maxLength: 64
                name: ClientToken
                required: false
                type: string
            -   description: 用户侧网络的网段，如需定义多个网段请使用用半角逗号字符隔开，最多支持3个网段
                in: query
                name: UserCidr
                required: false
                type: string
            produces:
            - application/xml
            - application/json
            responses:
                200:
                    description: Accept
                    schema:
                        properties:
                            RouteTableId:
                                description: 路由表 Id
                                name: RouteTableId
                                type: string
                            VRouterId:
                                description: 路由器 Id
                                name: VRouterId
                                type: string
                            VpcId:
                                description: 系统分配的专有网络 ID
                                name: VpcId
                                type: string
                        type: object
                400:
                    description: '{code: MissingParameter, describeen: The input parameter “Action” that is mandatory for processing this request is not supplied, describecn: 缺少 Action 字段}, {code: MissingParameter, describeen: The input parameter “AccessKeyId” that is mandatory for processing this request is not supplied, describecn: 缺少 AccessKeyId 字段}, {code: MissingParameter, describeen: An input parameter “Signature” that is mandatory for processing the request is not supplied., describecn: 缺少 Signature 字段}, {code: MissingParameter, describeen: The input parameter “TimeStamp” that is mandatory for processing this request is not supplied, describecn: 缺少 Timestamp 字段}, {code: MissingParameter, describeen: The input parameter “Version” that is mandatory for processing this request is not supplied, describecn: 缺少 Version 字段}, {code: InvalidParameter, describeen: The specified parameter “Action or Version” is not valid., describecn: 无效的 Action 值（该 API 不存在）}, {code: InvalidAccessKeyId.NotFound,
                        describeen: The Access Key ID provided does not exist in our records., describecn: 无效的 AccessKeyId 值（该 key 不存在）}, {code: IncompleteSignature, describeen: The request signature does not conform to Aliyun standards., describecn: 无效的 Signature 取值（签名结果错误）}, {code: InvalidParamater, describeen: The specified parameter “SignatureMethod” is not valid., describecn: 无效的 SignatureMethod 取值}, {code: InvalidParamater, describeen: The specified parameter “SignatureVersion” is not valid., describecn: 无效的 SignatureVersion 取值}, {code: IllegalTimestamp, describeen: The input parameter “Timestamp” that is mandatory for processing this request is not supplied., describecn: 无效的 Timestamp 取值（Timestamp 与服务器时间相差超过了 1 个小时）}, {code: SignatureNonceUsed, describeen: The request signature nonce has been used., describecn: 无效的 SignatureNonce（该 SignatureNonce 值已被使用过）}, {code: InvalidParameter, describeen: The specified parameter “Action or Version” is not valid., describecn: 无效的 Version 取值}, {code:
                        InvalidOwnerId, describeen: The specified OwnerId is not valid., describecn: 无效的 OwnerId 取值}, {code: InvalidOwnerAccount, describeen: The specified OwnerAccount is not valid., describecn: 无效的 OwnerAccount 取值}, {code: InvalidOwner, describeen: OwnerId and OwnerAccount can’t be used at one API access., describecn: 同时使用了 OwnerId 和 OwnerAccount}, {code: Throttling, describeen: Request was denied due to request throttling., describecn: 因系统流控拒绝访问}, {code: Throttling, describeen: Request was denied due to request throttling., describecn: 该 key 的调用 quota 已用完}, {code: UnsupportedParameter, describeen: The parameter ”&lt;parameter name&gt;” is not supported., describecn: 使用了无效的参数}, {code: UnsupportedParameter, describeen: The parameter ”&lt;parameter name&gt;” is not supported., describecn: 该参数无权使用}, {code: InsufficientBalance, describeen: Your account does not have enough balance., describecn: 余额不足}, {code: IdempotentParameterMismatch, describeen: Request uses a client token
                        in a previous request but is not identical to that request., describecn: 使用了一个已经使用过的 ClientToken，但此次请求内容却又与上一次使用该 Token 的 request 不一样.}, {code: InvalidParameter, describeen: The specified parameter is not valid, describecn: 参数校验失败},{code: InvalidParameter, describeen: Specified CIDR block is not valid ., describecn: 指定的网段不正确}, {code: ResourceNotAvailable, describeen: Resource you requested is not available in this region or zone., describecn: 指定的 Region 或 Zone 不支持 VPC}, {code: InvalidVpcName.Malformed, describeen: Specified VPC name is not valid., describecn: VPC 名称格式不正确}, {code: InvalidVpcDiscription.Malformed, describeen: Specified VPC description is not valid., describecn: 指定的 VPC 描述信息不正确}, {code: QuotaExceeded.Vpc, describeen: VPC quota exceeded., describecn: 用户名下的 VPC 数量达到配额上限}, {code: InvalidParameter, describeen: Specified  UserCidr  invalid  format., describecn: 指定的 UserCidr 格式不合法}, {code: InvalidParameter, describeen: Specified  UserCidr  Subnet mask is not
                        valid., describecn: 指定的 UserCidr 子网掩码不合法}, {code: InvalidUserCidr.Quota, describeen: Specified  UserCidr number is greater than 3., describecn: 指定的 UserCidr 个数大于3}, {code: InvalidUserCidr.Malformed, describeen: Specified  UserCidr  overlapping in of 100.64.0.0/10., describecn: 指定的 UserCidr 与 100.64.0.0/10 网段重叠}'
                403:
                    description: '{code: Forbidden.AccessKeyDisabled, describeen: The Access Key is disabled., describecn: 该 AccessKey 处于禁用状态}, {code: InvalidAction, describeen: Specified action is not valid., describecn: 该 key 无权调用该 API}, {code: UnsupportedHTTPMethod, describeen: This http method is not supported., describecn: 用户使用了不支持的 Http Method（当前 TOP 只支持 post 和 get）}, {code: MissingParameter, describeen: The input parameter OwnerId,OwnerAccount that is mandatory for processing this request is not supplied., describecn: 调用该接口没有指定 OwnerId}, {code: Forbidden.SubUser, describeen: The specified action is not available for you。, describecn: 无权调用订单类接口}, {code: Forbidden.RAM, describeen: User not authorized to operate the specified resource, or this API doesn’t support RAM., describecn: 使用了 RAM 授权子账号进行资源访问,但是本次操作没有被正确的授权}, {code: Forbidden.NotSupportRAM, describeen: This action does not support accessed by RAM mode., describecn: 该接口不允许使用 RAM 方式进行访问}, {code: RealNameAuthenticationError, describeen:
                        Your account has not passed the real-name authentication yet., describecn: 用户未进行实名认证}, {code: InvalidIdempotenceParameter.Mismatch, describeen: The specified parameters are different from before, describecn: 幂等参数不匹配}, {code: LastTokenProcessing, describeen: The last token request is processing, describecn: 上一次请求还在处理中},{code: Forbbiden, describeen: User not authorized to operate on the specified resource., describecn: 用户没有指定资源的操作权限}'
                404:
                    description: '{code: Forbidden.InstanceNotFound, describeen: The specified Instance is not found, so we cann’t get enough information to check permission in RAM., describecn: 使用了 RAM 授权子账号进行资源访问，但是本次访问涉及到的 Instance 不存在}, {code: Forbidden.DiskNotFound, describeen: The specified Disk is not found, so we cann’t get enough information to check permission in RAM., describecn: 使用了 RAM 授权子账号进行资源访问,但是本次访问涉及到的 Disk 不存在}, {code: Forbidden.SecurityGroupNotFound, describeen: The specified SecurityGroup is not found, so we cann’t get enough information to check permission in RAM., describecn: 使用了 RAM 授权子账号进行资源访问,但是本次访问涉及到的 SecurityGroup 不存在}, {code: Forbidden.SnapshotNotFound, describeen: The specified Snapshot is not found, so we cann’t get enough information to check permission in RAM., describecn: 使用了 RAM 授权子账号进行资源访问,但是本次访问涉及到的 Snapshot 不存在}, {code: Forbidden.ImageNotFound, describeen: The specified Image is not found, so we cann’t get enough information to check permission in
                        RAM., describecn: 使用了 RAM 授权子账号进行资源访问,但是本次访问涉及到的 Image 不存在},{code: InvalidRegionId.NotFound, describeen: Specified value of “RegionId” is not supported., describecn: 指定的 Region 不存在}'
                500:
                    description: '{code: ServiceUnavailable, describeen: The request has failed due to a temporary failure of the server., describecn: 服务不可用}, {code: InternalError, describeen: The request processing has failed due to some unknown error, exception or failure., describecn: 其他情况}'
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        summary: 在指定的地域创建 1 个 VPC
        x-requestsample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code></code></li><li class="L1"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//vpc.aliyuncs.com/?Action=CreateVpc</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">RegionID</span><span class="pun">=</span><span class="pln">cn</span><span class="pun">-</span><span class="pln">beijing</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 1
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code></code></li><li class="L1"><code><span class="pln">https</span><span class="pun">:</span><span class="com">//vpc.aliyuncs.com/?Action=CreateVpc</span></code></li><li class="L2"><code><span class="pun">&amp;</span><span class="typ">RegionID</span><span class="pun">=</span><span class="pln">cn</span><span class="pun">-</span><span class="pln">beijing</span></code></li><li class="L3"><code><span class="pun">&amp;&lt;公共请求参数&gt;</span></code></li></ol></pre>
            id: 2
        x-responsesample:
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-xml"><span class="tag">&lt;CreateVpcResponse&gt;</span></code></li><li class="L1"><code class="lang-xml"><span class="tag">&lt;RequestId&gt;</span><span class="pln">461D0C42-D5D1-4009-9B6A-B3D5888A19A9</span><span class="tag">&lt;/RequestId&gt;</span><span class="pln">,</span></code></li><li class="L2"><code class="lang-xml"><span class="pln">   </span><span class="tag">&lt;RouteTableId&gt;</span><span class="pln">vtb-25wm68mnh</span><span class="tag">&lt;/RouteTableId&gt;</span></code></li><li class="L3"><code class="lang-xml"><span class="pln">   </span><span class="tag">&lt;VRouterId&gt;</span><span class="pln">vrt-25bezkd03</span><span class="tag">&lt;/VRouterId&gt;</span></code></li><li class="L4"><code class="lang-xml"><span class="pln">   </span><span class="tag">&lt;VpcId&gt;</span><span class="pln">vpc-257gq642n</span><span class="tag">&lt;/VpcId&gt;</span></code></li><li
                class="L5"><code class="lang-xml"><span class="tag">&lt;/CreateVpcResponse&gt;</span></code></li></ol></pre>
            id: 1
            note: XML格式
        -   description: <pre class="prettyprint linenums prettyprinted" style=""><ol class="linenums"><li class="L0"><code class="lang-json"><span class="pun">{</span></code></li><li class="L1"><code class="lang-json"><span class="pln">  </span><span class="str">"RequestId"</span><span class="pun">:</span><span class="pln"> </span><span class="str">"461D0C42-D5D1-4009-9B6A-B3D5888A19A9"</span><span class="pun">,</span></code></li><li class="L2"><code class="lang-json"><span class="pln">  </span><span class="str">"RouteTableId"</span><span class="pun">:</span><span class="pln"> </span><span class="str">"vtb-25wm68mnh"</span><span class="pun">,</span></code></li><li class="L3"><code class="lang-json"><span class="pln">  </span><span class="str">"VRouterId"</span><span class="pun">:</span><span class="pln"> </span><span class="str">"vrt-25bezkd03"</span><span class="pun">,</span></code></li><li class="L4"><code class="lang-json"><span class="pln">  </span><span class="str">"VpcId"</span><span
                class="pun">:</span><span class="pln"> </span><span class="str">"vpc-257gq642n"</span></code></li><li class="L5"><code class="lang-json"><span class="pun">}</span></code></li></ol></pre>
            id: 2
            note: JSON格式
    /public:
        request:
            parameters:
            -   default: XML
                description: 返回值的类型，支持 JSON 与 XML。默认为 XML。
                enum:
                - XML
                - JSON
                in: query
                name: Format
                required: false
                type: string
            -   description: API 版本号，为日期形式：YYYY-MM-DD，本版本对应为 2014-05-26。
                in: query
                name: Version
                required: true
                type: string
            -   description: 阿里云颁发给用户的访问服务所用的密钥 ID。
                in: query
                name: AccessKeyId
                required: true
                type: string
            -   description: 签名结果串，关于签名的计算方法，请参见&lt;<a href="/document_detail/25492.html">签名机制</a>&gt;。
                in: query
                name: Signature
                required: true
                type: string
            -   description: 签名方式，目前支持 HMAC-SHA1。
                in: query
                name: SignatureMethod
                required: true
                type: string
            -   description: '        请求的时间戳。日期格式按照 <a href="/document_detail/25696.html">ISO8601</a> 标准表示，并需要使用 UTC 时间。格式为： <br />        YYYY-MM-DDThh:mm:ssZ <br />        例如，2014-05-26T12:00:00Z（为北京时间 2014 年 5 月 26 日 20 点 0 分 0 秒）。    '
                in: query
                name: Timestamp
                required: true
                type: string
            -   description: 签名算法版本，目前版本是 1.0。
                in: query
                name: SignatureVersion
                required: true
                type: string
            -   description: 唯一随机数，用于防止网络重放攻击。用户在不同请求间要使用不同的随机数值
                in: query
                name: SignatureNonce
                required: true
                type: string
            -   description: '本次 API 请求访问到的资源拥有者账户，即登录用户名。 <br />        此参数的使用方法，详见&lt; <a href="/document_detail/25494.html">借助 RAM 实现子账号对主账号的 ECS 资源访问</a> &gt;，（只能在 <a href="/document_detail/25496.html">RAM 中可对 ECS 资源进行授权的 Action</a> 中才能使用此参数，否则访问会被拒绝）    '
                in: query
                name: ResourceOwnerAccount
                required: false
                type: string
        response:
            RequestId:
                description: 用户发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: body
                name: RequestId
                type: string
swagger: '2.0'
x-vee: 2.0 AS
