host: "cs.aliyuncs.com"
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 容器服务（Container Service）提供高性能可伸缩的容器应用管理服务，支持用 Docker 容器进行应用生命周期管理，提供多种应用发布方式和持续交付能力并支持微服务架构。容器服务简化了容器管理集群的搭建工作，整合了阿里云虚拟化、存储、网络和安全能力，打造 Docker 云端最佳运行环境。
    title: aliyun object api
    version: '1.0'

paths:
    /public:
        request:
            parameters:
            -   description:  用于验证请求合法性的认证信息，采用 AccessKeyId:Signature 的形式。
                in: header
                name: Authorization
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容长度。
                in: header
                name: Content-Length
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容类型。
                in: header
                name: Content-Type
                required: true
                type: string     
            -   description:  用于验证请求合法性的认证信息，采用 AccessKeyId:Signature 的形式。
                in: header
                name: Content-MD5
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容长度。
                in: header
                name: Date
                required: true
                type: string
            -   description:  访问 Host 值，例如：diku.aliyuncs.com。
                in: header
                name: Host
                required: true
                type: string 
            -   description:  客户端需要的返回值类型，支持application/json 和 application/xml。
                enum:
                - application/json
                - application/xml
                in: header
                name: Accept
                required: true
                type: string 
            -   description:  地域（Region）指的是 ECS 实例所在的物理位置。更多详细信息参见 地域概念 和 ECS查询可用地域列表。
                in: header
                name: x-acs-region-id
                required: true
                type: string 
            -   description:  唯一随机数，用于防止网络重放攻击。您在不同请求间要使用不同的随机数值。
                in: header
                name: x-acs-signature-nonce
                required: true
                type: string 
            -   description:  用户签名方式，目前只支持HMAC-SHA1。
                enum:
                - HMAC-SHA1
                in: header
                name: x-acs-signature-method
                required: true
                type: string        
        response:
            RequestId:
                description:  您发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: body
                name: RequestId
                type: string    
    /CreateCluster/clusters:
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        post:
            description: 创建一个新的集群实例，并新建指定数量的节点。

            consumes:
            - application/xml
            - application/json
            
            parameters:
            -   description: 
                in: body
                name: ClusterCreation 
                required: true
                type: object
                schema:
                    type: object
                    properties:
                        data_disk_category:
                            description: ECS 使用的磁盘类型。更多详细信息，参见 <a href="/document_detail/25691.html">磁盘种类表</a>。
                            name: data_disk_category
                            required: true
                            type: string
                        data_disk_size:
                            description: 节点共享磁盘大小。
                            name: data_disk_size
                            required: true
                            type: integer
                        ecs_image_id:
                            description: ECS 使用的系统镜像 ID。
                                        如果您需要自定义集群的 ECS 镜像的 ID，需要保证 ECS 镜像满足以下条件：

                                        操作系统：Ubuntu、CentOS。
                                        Linux Kernel version ≥ 3.18，用于支持 overlayfs 以及 overlay network。
                                        镜像中删除 /etc/docker/key.json 文件。
                            enum:
                            -   ubuntu_14_0405_64_40G_base_20170222.vhd
                            -   centos_7_2_64_40G_base_20170222.vhd
                            name: ecs_image_id
                            required: false
                            type: string
                        instance_type:
                            description: ECS 规格类型代码。更多详细信息，参见 <a href="/document_detail/25378.html">实例规格族</a>。
                            name: instance_type
                            required: true
                            type: string
                        io_optimized:
                            description: 根据 ECS 实例规则来确定。取值为 none 或者 optimized。
                            enum:
                            -   none
                            -   optimized。
                            name: io_optimized
                            required: false
                            type: string
                        name:
                            description: 集群名称, 集群名称可以使用大小写英文字母、中文、数字、中划线。
                            name: name
                            required: true
                            type: string
                        network_mode:
                            description: '集群网络模式（经典网络: classic、VPC 网络: vpc）。'
                            name: network_mode
                            required: true
                            type: string
                        password:
                            description: root 账号密码。
                            name: password
                            required: true
                            type: string
                        size:
                            description: 集群 ECS 节点数量。
                            name: size
                            required: true
                            type: integer
                        subnet_cidr:
                            description: 集群可以使用的网络地址块，例如：192.168.24.0/22。只有网络模式为 vpc 的时候，才需要设置该字段。
                            name: subnet_cidr
                            required: true
                            type: string
                        vpc_id:
                            description: VPC 网络 ID。只有网络模式为 vpc 的时候，才需要设置该字段。更多详细信息，参见 <a href="/document_detail/27708.html">VPC 网络介绍</a>。
                            name: vpc_id
                            required: true
                            type: string
                        vswitch_id:
                            description: VPC 网络的交换机 ID。只有网络模式为 vpc 的时候，才需要设置该字段。
                            name: vswitch_id
                            required: true
                            type: string
    

            produces:
            - application/xml
            - application/json
            responses:
                202:
                    description: Accept
                    schema:
                        type: object
                        properties:
                            cluster_id:
                                description: 集群 ID，集群的唯一标识。
                                name: cluster_id
                                type: string
                            request_id:
                                description: 请求 ID
                                name: request_id
                                type: string
                            task_id:
                                description: 任务 ID
                                name: task_id
                                type: string
                        
        summary: 创建集群实例
        x-requestheader: '
                        POST /clusters HTTP/1.1
                        '
        x-requestbody: '
                        ClusterCreation { "name": "string",
                        "size": "number",
                        "network_mode": "string",
                        "subnet_cidr": "string",
                        "instance_type": "string",
                        "vpc_id": "string",
                        "vswitch_id": "string",
                        "password": "string",
                        "data_disk_size": "number",
                        "data_disk_category": "number"
                        "ecs_image_id": "string",
                        }

                        '
        x-responseheader: '
                        HTTP/1.1 202 Accepted
                        '
        x-responsebody: '
                        {
                            "cluster_id":"string",
                            "request_id":"string",
                            "task_id":"string"
                        }
                        '
        x-requestsample:  
        -   description: '
                        POST /clusters HTTP/1.1
                        <公共请求头>
                        {
                                "password": "Just$test",
                                "instance_type": "ecs.s2.small",
                                "name": "my-cluster-001",
                                "size": 2,
                                "network_mode": "classic",
                                "data_disk_category": "cloud",
                                "data_disk_size": 20,
                                "charge_type": "PayByTraffic",
                                "ecs_image_id":"ubuntu_14_0405_64_40G_base_20170222.vhd"
                        }
                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 202 Accepted
                        <公共响应头>
                        {
                            "cluster_id":"c01994faf5f364cc79b6ffb604061fa4a",
                            "request_id":"b44afc3c-46a4-4087-a215-c333a1218316",
                            "task_id":"T-8277xsdfsdf"
                        }
                        '
            id: 1