host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/DeleteBucketLifecycle:
        
        delete:
            description: 通过Delete Bucket Lifecycle来删除指定Bucket的生命周期配置。
                    1.	本操作会删除指定Bucket的所有的生命周期规则。此后，该Bucket中不会有Object被自动删除。
                    2.	如果Bucket或Lifecycle不存在，返回404 Not Found错误，错误码：NoSuchBucket或 NoSuchLifecycle。
                    3.	只有Bucket的拥有者才能删除Bucket的Lifecycle配置。如果试图操作一个不属于你的 Bucket，OSS返回403 Forbidden错误，错误码：AccessDenied。

            consumes:
            - application/x-www-form-urlencoded
            parameters: 
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:
                    description: success response
                403:
                    description: 只有Bucket的拥有者才能删除Bucket的Lifecycle配置。如果试图操作一个不属于你的Bucket，OSS返回403 Forbidden错误，错误码：AccessDenied。
                404:
                    description: 如果Bucket或Lifecycle不存在，返回404 Not Found错误，错误码：NoSuchBucket或 NoSuchLifecycle。
        summary: 删除Bucket中Object的生命周期规则
        x-requestformat: '
                       DELETE /?lifecycle HTTP/1.1
                        Host: BucketName.oss.aliyuncs.com
                        Date: GMT Date
                        Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        DELETE /?lifecycle HTTP/1.1
                        Host: oss-example.oss.aliyuncs.com
                        Date: Mon, 14 Apr 2014 01:17:35 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:6ZVHOehYzxoC1yxRydPQs/CnMZU=

                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 204 No Content
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Mon, 14 Apr 2014 01:17:35 GMT
                        Connection: keep-alive
                        Content-Length: 0
                        Server: AliyunOSS

                        '
            id: 1