host: BucketName.oss-cn-hangzhou.aliyuncs.com
x-vee: 2.0 AS
swagger: '2.0'
info:
    describe: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
path:
    /PutBucketLogging:
        describe: OSS提供Bucket访问日志的目的是为了方便bucket的拥有者理解和分析bucket的访问行为。OSS提供的 Bucket访问日志不保证记录下每一条访问记录。
                  Bucket的拥有者可以为bucket开启访问日志记录功能。这个功能开启后，OSS将自动记录访问这个bucket请求的详细信息，并按照用户指定的规则，以小时为单位，将访问日志作为一个Object写入用户指定的bucket。 OSS提供Bucket访问日志的目的是为了方便bucket的拥有者理解和分析bucket的访问行为。OSS提供的 Bucket访问日志不保证记录下每一条访问记录。
                  1.	源Bucket和目标Bucket必须属于同一个用户。
                  2.	上面所示的请求语法中，“BucketName”表示要开启访问日志记录的bucket；“TargetBucket”表示访问日志记录要存入的bucket；“TargetPrefix”表示存储访问日志记录的object名字前缀，可以为空。
                  3.	源bucket和目标bucket可以是同一个Bucket，也可以是不同的Bucket；用户也可以将多个的源 bucket的LOG都保存在同一个目标bucket内（建议指定不同的TargetPrefix）。
                  4.	当关闭一个Bucket的访问日志记录功能时，只要发送一个空的BucketLoggingStatus即可，具体方法可以参考下面的请求示例。
                  5.	所有PUT Bucket Logging请求必须带签名，即不支持匿名访问。
                  6.	如果PUT Bucket Logging请求发起者不是源bucket（请求示例中的BucketName）的拥有者，OSS返回403错误码；
                  7.	如果源bucket不存在，OSS返回错误码：NoSuchBucket。
                  8.	如果PUT Bucket Logging请求发起者不是目标bucket（请求示例中的TargetBucket）的拥有者，OSS返回403；如果目标bucket不存在，OSS返回错误码：InvalidTargetBucketForLogging。
                  9.	源Bucket和目标Bucket必须属于同一个数据中心，否则返回400错误，错误码为：InvalidTargetBucketForLogging。
                  10.	PUT Bucket Logging请求中的XML不合法，返回错误码：MalformedXML。
                  11.	源bucket和目标bucket可以是同一个Bucket；用户也可以将不同的源bucket的LOG都保存在同一个目标bucket内（注意要指定不同的TargetPrefix）。
                  12.	源Bucket被删除时，对应的Logging规则也将被删除。
                  13.	OSS以小时为单位生成bucket访问的Log文件，但并不表示这个小时的所有请求都记录在这个小时的LOG文件内，也有可能出现在上一个或者下一个LOG文件中。
                  14.	OSS生成的Log文件命名规则中的“UniqueString”仅仅是OSS为其生成的UUID，用于唯一标识该文件。
                  15.	OSS生成一个bucket访问的Log文件，算作一次PUT操作，并记录其占用的空间，但不会记录产生的流量。LOG生成后，用户可以按照普通的Object来操作这些LOG文件。
                  16.	OSS会忽略掉所有以“x-”开头的query-string参数，但这个query-string会被记录在访问LOG中。如果你想从海量的访问日志中，标示一个特殊的请求，可以在URL中添加一个“x-”开头的query-string参数。如： http://oss-example.oss-cn-hangzhou.aliyuncs.com/aliyun-logo.png http://oss-example.oss-cn-hangzhou.aliyuncs.com/aliyun-logo.png?x-user=admin OSS处理
                      上面两个请求，结果是一样的。但是在访问LOG中，你可以通过搜索“x-user=admin”，很方便地定位出经过标记的这个请求。
                  17.	OSS的LOG中的任何一个字段，都可能出现“-”，用于表示未知数据或对于当前请求该字段无效。
                  18.	根据需求，OSS的LOG格式将来会在尾部添加一些字段，请开发者开发Log处理工具时考虑兼容性的问题。
                  19.	如果用户上传了Content-MD5请求头，OSS会计算body的Content-MD5并检查一致性，如果不一致，将返回InvalidDigest错误码。
        put:
            consumes:
            - application/xml
            parameters:
            -   describe: ' 访问日志状态信息的容器 类型: 容器 子元素:   LoggingEnabled 父元素:   无 '
                in: formData
                name: BucketLoggingStatus
                require: true
                type: object
            -   describe: ' 访问日志信息的容器。这个元素在开启时需要，关闭时不需要。 类型: 容器 子元素:   TargetBucket, TargetPrefix 父元素:   BucketLoggingStatus '
                in: formData
                name: LoggingEnabled
                require: false
                type: object
                schema:
                    properties:
                      TargetBucket:
                          describe: ' 指定存放访问日志的Bucket。 类型: 字符 子元素: 无 父元素:   BucketLoggingStatus.LoggingEnabled '
                          in: formData
                          name: TargetBucket
                          require: 在开启访问日志的时候必需
                          type: string
                      TargetPrefix:
                          describe: ' 指定最终被保存的访问日志文件前缀。 类型:   字符 子元素:   None 父元素:   BucketLoggingStatus.LoggingEnabled '
                          in: formData
                          name: TargetPrefix
                          require: false
                          type: string
            produces:
            - application/xml
            responses:
                200:
                    description: success response
                    properties: {}
                400:
                    description: 源Bucket和目标Bucket必须属于同一个数据中心，否则返回400错误，错误码为：InvalidTargetBucketForLogging。             
                403:
                    description: 如果PUT Bucket Logging请求发起者不是源bucket（请求示例中的BucketName）的拥有者，OSS返回403错误码；
                                 如果PUT Bucket Logging请求发起者不是目标bucket（请求示例中的TargetBucket）的拥有者，OSS返回403；如果目标bucket不存在，OSS返回错误码：InvalidTargetBucketForLogging。
                default:
                    description: 如果源bucket不存在，OSS返回错误码：NoSuchBucket。
                                 PUT Bucket Logging请求中的XML不合法，返回错误码：MalformedXML。
                                 如果用户上传了Content-MD5请求头，OSS会计算body的Content-MD5并检查一致性，如果不一致，将返回InvalidDigest错误码。
        summary: 开启Bucket日志