host: BucketName.oss-cn-hangzhou.aliyuncs.com
x-vee: 2.0 AS
swagger: '2.0'
info:
    describe: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
path:
    /PutBucketLifecycle:
        describe: Bucket的拥有者可以通过Put Bucket Lifecycle来设置Bucket的Lifecycle配置。Lifecycle开启后，OSS将按照配置，定期自动删除与Lifecycle规则相匹配的Object。
                  1.	只有Bucket的拥有者才能发起Put Bucket Lifecycle请求，否则返回403 Forbidden消息。错误码：AccessDenied。
                  2.	如果此前没有设置过Lifecycle，此操作会创建一个新的Lifecycle配置；否则，就覆写先前的配置。
                  3.	可以对Object设置过期时间，也可以对Part设置过期时间。这里的Part指的是以分片上传方式上传，但最后未提交的分片。 
        put:
            consumes:
            - application/xml
            parameters:
            -   describe:  Lifecycle配置的容器，最多可容纳1000条规则。  类型：容器  子节点：Rule  父节点：无 
                in: formData
                maximum: '1000'
                name: LifecycleConfiguration
                require: true
                type: object
                schema:
                    properties:
                        Rule:
                            describe:  表述一条规则  类型：容器  子节点：ID，Prefix，Status，Expiration  父节点：LifecycleConfiguration 
                            enum:
                            - Prefix
                            in: formData
                            name: Rule
                            require: true
                            type: object
                            schema:
                                properties:
                                    Expiration:
                                        describe:  指定Object规则的过期属性。  类型：容器  子节点：Days或CreatedBeforeDate  父节点：Rule 
                                        in: formData
                                        name: Expiration
                                        require: false
                                        type: object
                                        schema:
                                            properties:
                                                Days:
                                                    describe:  指定规则在对象最后修改时间过后多少天生效。  类型：正整数  父节点：Expiration 
                                                    in: formData
                                                    name: Days
                                                    require: false
                                                    type: integer
                                                CreatedBeforeDate:
                                                    describe:  指定规则何时之前生效。日期必需服从ISO8601的格式，并且总是UTC的零点。 例如：2002-10-11T00:00:00.000Z 类型：字符串 父节点：Expiration或者AbortMultipartUpload
                                                    in: formData
                                                    name: CreatedBeforeDate
                                                    require: false
                                                    type: string
                                    ID:
                                        describe:  规则唯一的ID。最多由255字节组成。当用户没有指定，或者该值为空时，OSS会为用户生成一个唯一值。  类型：字符串  子节点：无  父节点：Rule 
                                        in: formData
                                        maxLength: '255'
                                        name: ID
                                        require: false
                                        type: string
                                    Prefix:
                                        describe:  指定规则所适用的前缀。只有匹配前缀的对象才可能被该规则所影响。不可重叠。  类型：字符串  子节点：无  父节点：Rule 
                                        in: formData
                                        name: Prefix
                                        require: true
                                        type: string
                                    Status:
                                        describe:  如果其值为Enabled，那么OSS会定期执行该规则；如果是Disabled，那么OSS会忽略该规则。  类型：字符串  父节点：Rule  有效值：Enabled，Disabled 
                                        enum:
                                        - Enabled
                                        - Disabled
                                        - Enabled
                                        - Disabled
                                        in: formData
                                        name: Status
                                        require: true
                                        type: string
                                    AbortMultipartUpload:
                                        describe:  指定未完成的Part规则的过期属性。  类型：容器  子节点：Days或CreatedBeforeDate   父节点：Rule 
                                        in: formData
                                        name: AbortMultipartUpload
                                        require: false
                                        type: object
                                        schema:
                                            properties:
                                                Days:
                                                    describe:  指定规则在对象最后修改时间过后多少天生效。  类型：正整数  父节点：Expiration 
                                                    in: formData
                                                    name: Days
                                                    require: false
                                                    type: integer
                                                CreatedBeforeDate:
                                                    describe:  指定规则何时之前生效。日期必需服从ISO8601的格式，并且总是UTC的零点。 例如：2002-10-11T00:00:00.000Z 类型：字符串 父节点：Expiration或者AbortMultipartUpload
                                                    in: formData
                                                    name: CreatedBeforeDate
                                                    require: false
                                                    type: string
                                type: object
                    type: object
            produces:
            - application/xml
            responses:
                200:
                    description: success response
                    properties: {}
                403:
                    description: 只有Bucket的拥有者才能发起Put Bucket Lifecycle请求，否则返回403 Forbidden消息。错误码：AccessDenied。
        produces:
        - text/xml
        summary: 设置Bucket中Object的生命周期规则