host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/GetBucketAcl/?acl:
        
        get:
            description: Get Bucket ACL用来获取某个Bucket的访问权限。
            consumes:
            - application/x-www-form-urlencoded
            parameters:
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:

                    description: success response
                    schema:
                        type: object
                        properties:
                            AccessControlPolicy:
                                description:  保存Get   Bucket ACL结果的容器 类型：容器 父节点：None 
                                in: formData
                                name: AccessControlPolicy
                                type: object
                                properties:
                                    AccessControlList:
                                        description:  存储ACL信息的容器 类型：容器 父节点：AccessControlPolicy 
                                        in: formData
                                        name: AccessControlList
                                        type: object
                                        properties:
                                            Grant:
                                                description:  Bucket的ACL权限。 类型：枚举字符串 有效值：private、public-read、public-read-write 父节点：AccessControlPolicy.AccessControlList 
                                                enum: 
                                                - private
                                                - public-read
                                                - public-read-write
                                                in: formData
                                                name: Grant
                                                type: string
                                        
                                    Owner:
                                        description:  保存Bucket拥有者信息的容器。 类型：容器 父节点：AccessControlPolicy 
                                        in: formData
                                        name: Owner
                                        type: object
                                        properties:
                                            DisplayName:
                                                description:  Bucket拥有者的名称.。(目前和ID一致) 类型：字符串 父节点：AccessControlPolicy.Owner 
                                                in: formData
                                                name: DisplayName
                                                type: string
                                            ID:
                                                description:  Bucket拥有者的用户ID 类型：字符串 父节点：AccessControlPolicy.Owner 
                                                in: formData
                                                name: ID
                                                type: string
        summary: 获得Bucket访问权限
        x-requestformat: '
                        GET /?acl HTTP/1.1
                        Host: BucketName.oss-cn-hangzhou.aliyuncs.com
                        Date: GMT Date Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        GET /?acl HTTP/1.1
                        Host: oss-example.oss-cn-hangzhou.aliyuncs.com
                        Date: Fri, 24 Feb 2012 04:11:23 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:CTkuxpLAi4XZ+WwIfNm0FmgbrQ0=

                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 200 OK
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Fri, 24 Feb 2012 04:11:23 GMT
                        Content-Length: 253
                        Content-Tupe: application/xml
                        Connection: keep-alive Server: AliyunOSS
                        <?xml version="1.0" ?>
                        <AccessControlPolicy>
                            <Owner>
                                <ID>00220120222</ID>
                                <DisplayName>user_example</DisplayName>
                            </Owner>
                            <AccessControlList>
                                <Grant>public-read</Grant>
                            </AccessControlList> </AccessControlPolicy>

                        '
            id: 1