host: "cs.aliyuncs.com"
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 容器服务（Container Service）提供高性能可伸缩的容器应用管理服务，支持用 Docker 容器进行应用生命周期管理，提供多种应用发布方式和持续交付能力并支持微服务架构。容器服务简化了容器管理集群的搭建工作，整合了阿里云虚拟化、存储、网络和安全能力，打造 Docker 云端最佳运行环境。
    title: aliyun object api
    version: '1.0'

paths:
    /public:
        request:
            parameters:
            -   description:  用于验证请求合法性的认证信息，采用 AccessKeyId:Signature 的形式。
                in: header
                name: Authorization
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容长度。
                in: header
                name: Content-Length
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容类型。
                in: header
                name: Content-Type
                required: true
                type: string     
            -   description:  用于验证请求合法性的认证信息，采用 AccessKeyId:Signature 的形式。
                in: header
                name: Content-MD5
                required: true
                type: string
            -   description:  RFC 2616 中定义的 HTTP 请求内容长度。
                in: header
                name: Date
                required: true
                type: string
            -   description:  访问 Host 值，例如：diku.aliyuncs.com。
                in: header
                name: Host
                required: true
                type: string 
            -   description:  客户端需要的返回值类型，支持application/json 和 application/xml。
                enum:
                - application/json
                - application/xml
                in: header
                name: Accept
                required: true
                type: string 
            -   description:  地域（Region）指的是 ECS 实例所在的物理位置。更多详细信息参见 地域概念 和 ECS查询可用地域列表。
                in: header
                name: x-acs-region-id
                required: true
                type: string 
            -   description:  唯一随机数，用于防止网络重放攻击。您在不同请求间要使用不同的随机数值。
                in: header
                name: x-acs-signature-nonce
                required: true
                type: string 
            -   description:  用户签名方式，目前只支持HMAC-SHA1。
                enum:
                - HMAC-SHA1
                in: header
                name: x-acs-signature-method
                required: true
                type: string        
        response:
            RequestId:
                description:  您发送的每次接口调用请求，无论成功与否，系统都会返回一个唯一识别码
                in: query
                name: RequestId
                type: string    
    /GetClusterList/clusters?name={name}:
        parameter:
            $ref: '#/paths/"/public"/request/parameters'
        get:
            description: 查看您在容器服务中创建的所有集群。如果传递了 name 参数，则只返回指定集群的详情。

            consumes:
            - application/xml
            - application/json
            parameters:
            -   description: 集群名称
                in: path
                name: name
                required: true
                type: string
            produces:
            - application/xml
            - application/json
            responses:
                200:
                    description: OK
                    schema:
                        type: array
                        items:
                            x-schema:
                                type: object
                                properties:
                                    agent_version:
                                        description: Agent 版本号。
                                        
                                        name: agent_version
                                        type: string
                                    cluster_id:
                                        description: 集群 ID，集群的唯一标识。
                                        
                                        name: cluster_id
                                        type: string
                                    created:
                                        description: 集群的创建时间。
                                        
                                        name: created
                                        type: string
                                    external_loadbalancer_id:
                                        description: 集群负载均衡服务的 ID。
                                        
                                        name: external_loadbalancer_id
                                        type: string
                                    master_url:
                                        description: 集群 Master 地址，您可以通过该地址连接您的集群进行相关操作。更多详细信息，参见 <a href="/document_detail/25983.html">通过 Docker 工具连接集群</a>。
                                        
                                        name: master_url
                                        type: string
                                    name:
                                        description: 集群名称，由您在创建集群时指定，在每个用户下唯一。
                                        
                                        name: name
                                        type: string
                                    network_mode:
                                        description: '集群网络模式（经典网络: classic、VPC 网络: vpc）。'
                                        
                                        name: network_mode
                                        type: string
                                    region_id:
                                        description: 集群所在地域 ID。更多详细信息，参见 <a href="/document_detail/40654.html">地域</a>。
                                        
                                        name: region_id
                                        type: string
                                    security_group_id:
                                        description: 安全组 ID。
                                        
                                        name: security_group_id
                                        type: string
                                    size:
                                        description: 节点数。
                                        
                                        name: size
                                        type: string
                                    state:
                                        description: 集群状态。更多详细信息，参见 <a href="/document_detail/26005.html">集群的生命周期</a>。
                                        
                                        name: state
                                        type: string
                                    updated:
                                        description: 最后更新时间。
                                        
                                        name: updated
                                        type: string
                                    vpc_id:
                                        description: VPC ID。
                                        
                                        name: vpc_id
                                        type: string
                                    vswitch_id:
                                        description: vswitch ID。
                                        
                                        name: vswitch_id
                                        type: string
        summary: 查看所有集群实例
        x-requestheader: '
                        GET /clusters?name={name} HTTP/1.1
                        '
        x-requestbody: '
                      
                        '
        x-responseheader: '
                        HTTP/1.1 200 OK
                        '
        x-responsebody: '
                        [
                            {
                                "agent_version": "string",
                                "cluster_id": "string",
                                "created": "datetime",
                                "external_loadbalancer_id": "string",
                                "master_url": "string",
                                "name": "string",
                                "network_mode": "string",
                                "region_id": "string",
                                "security_group_id": "string",
                                "size": "numbers",
                                "state": "string",
                                "updated": "datetime",
                                "vpc_id": "string",
                                "vswitch_id": "string"
                            }
                        ]
                        '
        x-requestsample:  
        -   description: '
                        GET /clusters HTTP/1.1
                        <公共请求头>
                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 200 OK
                        <公共响应头>
                        [
                        {
                        "agent_version": "0.5-e56dab3",
                        "cluster_id": "c978ca3eaacd3409a9437db07598f1f69",
                        "created": "2015-12-11T03:52:40Z",
                        "external_loadbalancer_id": "1518f2b7e4c-cn-beijing-btc-a01",
                        "master_url": "https://182.92.245.56:17589",
                        "name": "my-python-cluster-039de960",
                        "network_mode": "classic",
                        "region_id": "cn-beijing",
                        "security_group_id": "sg-25yqjuxhz",
                        "size": 5,
                        "state": "running",
                        "updated": "2015-12-15T15:01:58Z",
                        "vpc_id": "",
                        "vswitch_id": ""
                        },
                        {
                        "agent_version": "0.5-e56dab3",
                        "cluster_id": "c1eb19e0093204cbb86c3a80334d2129e",
                        "created": "2015-12-15T14:26:58Z",
                        "external_loadbalancer_id": "151a6099de1-cn-beijing-btc-a01",
                        "master_url": "https://182.92.245.56:11905",
                        "name": "my-test-cluster-002b3f3d",
                        "network_mode": "classic",
                        "region_id": "cn-beijing",
                        "security_group_id": "sg-25rg2ws9f",
                        "size": 1,
                        "state": "running",
                        "updated": "2015-12-15T14:43:55Z",
                        "vpc_id": "",
                        "vswitch_id": ""
                        }
                        ]


                        '
            id: 1