host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/GetSymlink/{ObjectName}?symlink:
        get:
            description: 用于获取符号链接，此操作要求用户对该符号链接有读权限。
            consumes:
            - application/x-www-form-urlencoded
            parameters: 
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            -   description:  容器名
                in: path
                name: ObjectName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:
                    description: success response
                    schema:
                        type: object
                        properties:
                            x-oss-symlink-target:
                                description:  符号链接指向的目标文件。 类型：字符串
                                in: header
                                name: x-oss-symlink-target
                                required: true
                                type: string
        x-requestformat: '
                        GET /ObjectName?symlink HTTP/1.1
                        Host: BucketName.oss-cn-hangzhou.aliyuncs.com Date: GMT Date
                        Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        GET /link-to-oss.jpg?symlink HTTP/1.1
                        Host: oss-example.oss-cn-hangzhou.aliyuncs.com
                        Date: Fri, 24 Feb 2012 06:38:30 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:UNQDb7GapEgJCZkcde6OhZ9Jfe8=

                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 200 OK
                        Server: AliyunOSS
                        Date: Fri, 24 Feb 2012 06:38:30 GMT
                        Last-Modified: Fri, 24 Feb 2012 06:07:48 GMT
                        Content-Length: 0 Connection: keep-alive
                        x-oss-request-id: 5650BD72207FB30443962F9A x-oss-symlink-target: oss.jpg
                        ETag: "A797938C31D59EDD08D86188F6D5B872"


                        '
            id: 1