host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/GetBucketLogging/?logging:
        
        get:
            description: Get Bucket Logging用于查看Bucket的访问日志配置情况。
                    1.	如果Bucket不存在，返回404 no content错误。错误码：NoSuchBucket。
                    2.	只有Bucket的拥有者才能查看Bucket的访问日志配置情况，否则返回403 Forbidden错误,错误码：AccessDenied。
                    3.	如果源Bucket未设置Logging规则，OSS仍然返回一个XML消息体，但其中的BucketLoggingStatus元素为空。

            consumes:
            - application/x-www-form-urlencoded
            parameters: 
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:
                    description: success response
                    schema:
                        type: object
                        properties:
                            BucketLoggingStatus:
                                description: ' 访问日志状态信息的容器 类型: 容器 子元素:   LoggingEnabled 父元素:   无 '
                                in: formData
                                name: BucketLoggingStatus
                                type: object
                                properties:
                                    LoggingEnabled:
                                        description: ' 访问日志信息的容器。这个元素在开启时需要，关闭时不需要。 类型: 容器 子元素:   TargetBucket, TargetPrefix 父元素:   BucketLoggingStatus '
                                        in: formData
                                        name: LoggingEnabled
                                        type: object
                                        properties:
                                            TargetBucket:
                                                description: ' 指定存放访问日志的Bucket。 类型: 字符 子元素:   无 父元素:   BucketLoggingStatus.LoggingEnabled '
                                                in: formData
                                                name: TargetBucket
                                                type: string
                                            TargetPrefix:
                                                description: ' 指定最终被保存的访问日志文件前缀。 类型:   字符 子元素:   None 父元素:   BucketLoggingStatus.LoggingEnabled '
                                                in: formData
                                                name: TargetPrefix
                                                type: string
                403:
                    description: 只有者才能查看Bucket的访问日志配置情况，否则返回403 Forbidden错误,错误码：AccessDenied。
                404:
                    description: 如果Bucket不存在，返回404 no content错误。错误码：NoSuchBucket。
        summary: 在Object尾追加上传数据
        x-requestformat: '
                        GET /?logging HTTP/1.1
                        Host: BucketName.oss-cn-hangzhou.aliyuncs.com
                        Date: GMT Date
                        Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        Get /?logging HTTP/1.1
                        Host: oss-example.oss-cn-hangzhou.aliyuncs.com
                        Date: Fri, 04 May 2012 05:31:04 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:ceOEyZavKY4QcjoUWYSpYbJ3naA=

                        '
            id: 1
        -   description: '
                        Get /?logging HTTP/1.1
                        Host: oss-example.oss-cn-hangzhou.aliyuncs.com
                        Date: Fri, 04 May 2012 05:31:04 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:ceOEyZavKY4QcjoUWYSpYbJ3naA=

                        '
            id: 2
        x-responsesample:
        -   description: '
                        HTTP/1.1 200
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Fri, 04 May 2012 05:31:04 GMT
                        Connection: keep-alive
                        Content-Length: 210
                        Server: AliyunOSS
                        <?xml version="1.0" encoding="UTF-8"?>
                        <BucketLoggingStatus xmlns=”http://doc.oss-cn-hangzhou.aliyuncs.com”>
                            <LoggingEnabled>
                                <TargetBucket>mybucketlogs</TargetBucket>
                                <TargetPrefix>mybucket-access_log/</TargetPrefix>
                            </LoggingEnabled>
                        </BucketLoggingStatus>

                        '
            id: 1
            note: 已设置LOG规则的返回示例
        -   description: '
                        HTTP/1.1 200 x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Fri, 04 May 2012 05:31:04 GMT
                        Connection: keep-alive
                        Content-Length: 110
                        Server: AliyunOSS
                        <?xml version="1.0" encoding="UTF-8"?>
                        <BucketLoggingStatus xmlns=”http://doc.oss-cn-hangzhou.aliyuncs.com”>
                        </BucketLoggingStatus>

                        '
            id: 2
            note: 未设置LOG规则的返回示例