host: ""
x-vee: 2.0 AS
swagger: '2.0'
info:
    description: 阿里云对象存储服务（Object Storage Service，简称OSS），是阿里云对外提供的海量，安全，低成本，高可靠的云存储服务。用户可以通过本文档提供的简单的REST接口，在任何时间、任何地点、任何互联网设备上进行上传和下载数据。基于OSS，用户可以搭建出各种多媒体分享网站、网盘、个人和企业数据备份等基于大规模数据的服务。
    title: aliyun oss api
    version: '1.0'
paths:
    /{BucketName}.oss-cn-hangzhou.aliyuncs.com/GetBucketLocation/?location:
        get:
            description: Get Bucket Location用于查看Bucket所属的数据中心位置信息。
                     1.	只有Bucket的拥有者才能查看Bucket的Location信息，否则返回403 Forbidden错误,错误码：AccessDenied。
                     2.	目前LocationConstraint有效值：oss-cn-hangzhou，oss-cn-qingdao，oss-cn-beijing，osscn-hongkong，oss-cn-shenzhen，oss-cn-shanghai，oss-us-west-1，oss-us-east-1，oss-ap-southeast-1；分别对应杭州数据中心，青岛数据中心，北京数据中心、香港数据中心、深圳数据中心、上海数据中心、美国硅谷数据中心、美国弗吉尼亚数据中心和亚太（新加坡）数据中心。
            consumes:
            - application/x-www-form-urlencoded
            parameters: 
            -   description:  对象名
                in: path
                name: BucketName
                required: true
                type: string
            produces:
            - application/x-www-form-urlencoded
            responses:
                200:
                    description: success response
                    schema:
                        type: object
                        properties:
                            LocationConstraint:
                                description: Bucket所在的区域 类型：字符串 Values：oss-cn-hangzhou、oss-cn-qingdao、oss-cn-beijing、oss-cn-hongkong、oss-cn-shenzhen、oss-cn-shanghai 
                                in: formData
                                name: LocationConstraint
                                type: string
                                enum:
                                - oss-cn-hangzhou
                                - oss-cn-qingdao
                                - oss-cn-beijing
                                - oss-cn-hongkong
                                - oss-cn-shenzhen
                                - oss-cn-shanghai
                403:
                    description: 只有Bucket的拥有者才能查看Bucket的Location信息，否则返回403 Forbidden错误,错误码：AccessDenied。
        summary: 获得Bucket所属的数据中心位置信息
        x-requestformat: '
                        GET /?location HTTP/1.1
                        Host: BucketName.oss-cn-hangzhou.aliyuncs.com Date: GMT Date
                        Authorization: SignatureValue

                        '
        x-requestsample:  
        -   description: '
                        Get /?location HTTP/1.1
                        Host: oss-example.oss-cn-hangzhou.aliyuncs.com
                        Date: Fri, 04 May 2012 05:31:04 GMT
                        Authorization: OSS qn6qrrqxo2oawuk53otfjbyc:ceOEyZavKY4QcjoUWYSpYbJ3naA=

                        '
            id: 1
        x-responsesample:
        -   description: '
                        HTTP/1.1 200
                        x-oss-request-id: 534B371674E88A4D8906008B
                        Date: Fri, 15 Mar 2013 05:31:04 GMT
                        Connection: keep-alive
                        Content-Length: 90
                        Server: AliyunOSS
                        <?xml version="1.0" encoding="UTF-8"?>
                        <LocationConstraint xmlns=”http://doc.oss-cn-hangzhou.aliyuncs.com”>oss-cn-hangzhou</LocationConstraint
                        '
            id: 1